# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'

feverous:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.feverous_split.feverous_ctxs
  id_prefix: 'feverous:'