# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  #file: data.wikipedia_split.psgs_w100
  file: /private/home/vladk/data/wikipedia/wiki_passages/psgs_w100.tsv
  id_prefix: 'wiki:'

cc_news:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /checkpoint/piktus/cc-news/cc_news_processed.tsv

cc_news_small:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /checkpoint/piktus/cc-news/cc_news_processed_small.tsv