datasets:
  nq_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: /checkpoint/vladk/dpr_open_source/biencoder-nq-train.json

  nq_train_hn1:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: /checkpoint/vladk/biencoder/validate_nq_hf_bert_bsz16_lr2e5_wd00_max_grad2/nq-train-dense-results_as_input_with_gold.json

  nq_dev:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: /checkpoint/vladk/dpr_open_source/biencoder-nq-dev.json

  nq_dev_kilt:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/nq-dev-multikilt.json

  # NQ Tables
  nq_train_tables_short_answers:
    _target_: dpr.data.biencoder_data.JsonLTablesQADataset
    file: /checkpoint/vladk/datasets/tables/dpr.nq_train.tables.whole.bm25.jsonl
    is_train_set: True
    shuffle_positives: True
    max_len: 100
    split_type: type4

  nq_test_tables_short_answers:
    _target_: dpr.data.biencoder_data.JsonLTablesQADataset
    file: /checkpoint/vladk/datasets/tables/dpr.nq_test.tables.whole.bm25.jsonl
    is_train_set: False
    shuffle_positives: False
    max_len: 100
    split_type: type4

  nq_train_tables_long_answers:
    _target_: dpr.data.biencoder_data.JsonLTablesQADataset
    file: /checkpoint/vladk/datasets/tables/dpr.nq_train.long_ans.tables.whole.jsonl
    is_train_set: True
    shuffle_positives: True
    max_len: 100
    split_type: type3

  trivia_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: /checkpoint/vladk/dpr_open_source/triviaqa-train.json

  curated_trec_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: /private/home/scottyih/share/qa_encoder_training/curatedtrec-train.no_empty_positive.json

  webquestions_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    file: /private/home/scottyih/share/qa_encoder_training/webquestions-train.no_empty_positive.json
