# @package _group_

nq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: /checkpoint/vladk/dpr_open_source/biencoder-nq-train.json
  #file: data.retriever.nq-train

nq_train_hn1:
  _target_: dpr.data.biencoder_data.JsonQADataset
  #file: data.retriever.nq-adv-hn-train
  file: /checkpoint/vladk/biencoder/validate_nq_hf_bert_bsz16_lr2e5_wd00_max_grad2/nq-train-dense-results_as_input_with_gold.json

nq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  #file: data.retriever.nq-dev
  file: /checkpoint/vladk/dpr_open_source/biencoder-nq-dev.json

trivia_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-train

trivia_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-dev

squad1_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-train

squad1_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-dev

webq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-train

webq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-dev

curatedtrec_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-train

curatedtrec_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-dev


nq_speech_mixed_train:
  _target_: dpr.data.speech_data.WavJsonTextDataset
  json_file: /checkpoint/vladk/dpr_open_source/biencoder-nq-train.json
  wav_tsv_file: /checkpoint/vladk/speechqa/data/train/train.tsv
  normalize_audio: False

nq_speech_mixed_dev:
  _target_: dpr.data.speech_data.WavJsonTextDataset
  json_file: /checkpoint/vladk/dpr_open_source/biencoder-nq-dev.json
  wav_tsv_file: /checkpoint/vladk/speechqa/data/dev/dev.tsv
  normalize_audio: False

nq_speech_quantized_train:
  _target_: dpr.data.speech_data.QuantizedJsonTextDataset
  json_file: /checkpoint/vladk/dpr_open_source/biencoder-nq-train.json
  wav_tsv_file: /checkpoint/vladk/speechqa/data/train/train.tsv
  km_file: /checkpoint/kushall/data/speechqa/hubert_clustering/layer6_km100/train_deduped_0_1.km
  max_audio_len: 176

nq_speech_quantized_dev:
  _target_: dpr.data.speech_data.QuantizedJsonTextDataset
  json_file: /checkpoint/vladk/dpr_open_source/biencoder-nq-dev.json
  wav_tsv_file: /checkpoint/vladk/speechqa/data/dev/dev.tsv
  km_file: /checkpoint/kushall/data/speechqa/hubert_clustering/layer6_km100/dev_deduped_0_1.km
  max_audio_len: 176

paq_4m_speech_mixed_train:
  _target_: dpr.data.speech_data.WavPAQTextDataset
  jsonl_file: /private/home/barlaso/data/paq/PAQ.dpr.train.jsonl
  manifest_txt_file: /checkpoint/kushall/data/speechqa/paq/PAQ.dpr.train_questions.txt
  wav_root_dir: /checkpoint/kushall/data/speechqa/paq/PAQ.dpr.train_questions_audio/denoised/
  normalize_audio: False
  total_data_size: 4000000

