datasets:
  nq_train_kilt:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/nq-train-multikilt.json
    normalize: True
    shuffle_positives: True
    query_special_suffix: '?'

  nq_dev_kilt:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/nq-dev-multikilt.json
    normalize: True
    query_special_suffix: '?'

  aidayago2_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/aidayago2-dev-multikilt.json
    special_token: '[START_ENT]'
    selector:
      _target_: dpr.data.biencoder_data.RepSpecificTokenSelector
      token: '[START_ENT]'
    normalize: True
    shuffle_positives: True

  aidayago2_dev:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/aidayago2-train-multikilt.json
    special_token: '[START_ENT]'
    selector:
      _target_: dpr.data.biencoder_data.RepSpecificTokenSelector
      token: '[START_ENT]'
    normalize: True

  fever_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/fever-train-multikilt.json
    normalize: True
    shuffle_positives: True

  fever_dev:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/fever-dev-multikilt.json
    normalize: True

  wow_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/wow-train-multikilt.json
    normalize: True
    shuffle_positives: True

  trivia_train_kilt:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/triviaqa-train-multikilt.json
    normalize: True
    shuffle_positives: True
    query_special_suffix: '?'

  trivia_dev_kilt:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/triviaqa-dev-multikilt.json
    normalize: True
    query_special_suffix: '?'

  zeroshot_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/zeroshot-train-multikilt.json
    normalize: True
    shuffle_positives: True

  zeroshot_dev:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/zeroshot-dev-multikilt.json
    normalize: True

  hotpot_train_kilt:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/hotpotqa-train-multikilt.json
    normalize: True
    shuffle_positives: True
    query_special_suffix: '?'

  hotpot_dev_kilt:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/hotpotqa-dev-multikilt.json
    normalize: True
    query_special_suffix: '?'

  trex_train:
    _target_: dpr.data.biencoder_data.JsonQADataset
    data_file_pattern: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/trex-train-multikilt.json
    normalize: True
    shuffle_positives: True
