# @package _group_

nq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  #file: data.retriever.qas.nq-test
  file: /private/home/scottyih/playground/bert-qa/data/nq-test.qa.csv

nq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-train

nq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-dev

trivia_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  #file: data.retriever.qas.trivia-test
  file: /private/home/scottyih/playground/bert-qa/data/triviaqa-test.qa.csv

trivia_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-train

trivia_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-dev

nq_audio_test:
  _target_: dpr.data.speech_data.WavTextQADataset
  #file: data.retriever.qas.nq-test
  file: /private/home/scottyih/playground/bert-qa/data/nq-test.qa.csv
  wav_tsv_file: /checkpoint/vladk/speechqa/data/test/test.tsv
  #normalize_audio: True
  normalize_audio: False

nq_tts_asr_test:
  _target_: dpr.data.retriever_data.TTS_ASR_QASrc
  file: /private/home/scottyih/playground/bert-qa/data/nq-test.qa.csv
  trans_file: /checkpoint/vladk/speechqa/data/test/transcriptions/hypo.word-960h_scratch.pt-test.txt

nq_tts_asr_test2:
    _target_: dpr.data.retriever_data.TTS_ASR_QASrc
    file: /private/home/scottyih/playground/bert-qa/data/nq-test.qa.csv
    trans_file: /checkpoint/kushall/data/speechqa/transcription_test/hypo.word-wav2vec_small_960h.pt-test.txt