datasets:
  nq_test_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/nq-test-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/nq-test-kilt.jsonl
    special_query_token: '[Q]'

  trivia_test_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/triviaqa-test-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/triviaqa-test-multikilt.tsv
    special_query_token: '[Q]'

  trivia_dev_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/triviaqa-dev-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/triviaqa-dev-kilt.jsonl
    special_query_token: '[Q]'

  zeroshot_test_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/zeroshot-test-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/datasets/structured_zeroshot-test_without_answers-kilt.jsonl

  zeroshot_dev_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/zeroshot-dev-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/zeroshot-dev-kilt.jsonl

  fever_dev_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/fever-dev-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/fever-dev-kilt.jsonl
    special_query_token: '[F]'

  ay_dev_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/aidayago2-dev-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/aidayago2-dev-kilt.jsonl
    special_query_token: '[START_ENT]'
    selector:
      class: dpr.data.biencoder_data.RepSpecificTokenSelector
      params:
        token: '[START_ENT]'

  ay_test_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/aidayago2-test-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/datasets/aidayago2-test_without_answers-kilt.jsonl
    special_query_token: '[START_ENT]'
    selector:
      class: dpr.data.biencoder_data.RepSpecificTokenSelector
      params:
        token: '[START_ENT]'