datasets:
  nq_test:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: /private/home/scottyih/playground/bert-qa/data/nq-test.qa.csv

  nq_train:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: /private/home/scottyih/playground/bert-qa/data/nq-train.qa.csv

  nq_dev:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: /private/home/scottyih/playground/bert-qa/data/nq-dev.qa.csv

  nq_tables_test:
    _target_: dpr.data.retriever_data.JsonlQASrc
    file: /checkpoint/vladk/datasets/tables/dpr.nq_test.tables.whole.bm25.jsonl

  nq_new_dev:
    _target_: dpr.data.retriever_data.JsonlQASrc
    file: /private/home/vladk/src/natural-questions/nq_open/NQ-open.efficientqa.dev.1.1.jsonl
    answers_attr: answer

  nq_new_test:
    _target_: dpr.data.retriever_data.JsonlQASrc
    file: /private/home/vladk/src/testdata/NQ-open.efficientqa.test.1.1.no-annotations.jsonl

  nq_dev_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/nq-dev-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/nq-dev-kilt.jsonl

  nq_dev_kilt_ans:
    _target_: dpr.data.retriever_data.KiltJsonlQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/nq-dev-kilt.jsonl
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/nq-dev-kilt.jsonl

  nq_test_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/nq-test-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/nq-test-kilt.jsonl

  nq_test_kilt_ans:
    _target_: dpr.data.retriever_data.KiltJsonlQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/nq-test-kilt.jsonl
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/nq-test-kilt.jsonl

  trivia_test:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: /private/home/scottyih/playground/bert-qa/data/triviaqa-test.qa.csv

  trivia_train:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: /private/home/scottyih/playground/bert-qa/data/triviaqa-train.qa.csv

  trivia_dev:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: /private/home/scottyih/playground/bert-qa/data/triviaqa-dev.qa.csv

  curatedtrec_test:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: /private/home/scottyih/playground/bert-qa/data/curatedtrec-test.qa.csv

  curatedtrec_dev:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: /private/home/scottyih/playground/bert-qa/data/curatedtrec-dev.qa.csv

  curatedtrec_train:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: /private/home/scottyih/playground/bert-qa/data/curatedtrec-train.qa.csv

  webquestions_test:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: /private/home/scottyih/playground/bert-qa/data/webquestions-test.qa.csv

  webquestions_dev:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: /private/home/scottyih/playground/bert-qa/data/webquestions-dev.qa.csv

  webquestions_train:
    _target_: dpr.data.retriever_data.CsvQASrc
    file: /private/home/scottyih/playground/bert-qa/data/webquestions-train.qa.csv


  trivia_test_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/triviaqa-test-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/triviaqa-test-multikilt.tsv

  trivia_dev_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/triviaqa-dev-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/triviaqa-dev-kilt.jsonl

  zeroshot_test_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/zeroshot-test-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/datasets/structured_zeroshot-test_without_answers-kilt.jsonl

  zeroshot_dev_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/zeroshot-dev-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/zeroshot-dev-kilt.jsonl

  fever_dev_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/fever-dev-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/fever-dev-kilt.jsonl

  ay_dev_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/aidayago2-dev-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/aidayago2-dev-kilt.jsonl
    special_query_token: '[START_ENT]'
    selector:
      class: dpr.data.biencoder_data.RepSpecificTokenSelector
      params:
        token: '[START_ENT]'

  ay_test_kilt:
    _target_: dpr.data.retriever_data.KiltCsvQASrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/aidayago2-test-multikilt.tsv
    kilt_gold_file: /checkpoint/fabiopetroni/KILT/datasets/aidayago2-test_without_answers-kilt.jsonl
    special_query_token: '[START_ENT]'
    selector:
      class: dpr.data.biencoder_data.RepSpecificTokenSelector
      params:
        token: '[START_ENT]'

  toy_test:
    _target_: dpr.data.retriever_data.ToyQASrc

  music_train:
    _target_: dpr.data.retriever_data.MusicCsvQASrc
    file: /private/home/xilun/hybridqa/musicqa/split/musicqa_train.tsv

  music_dev:
    _target_: dpr.data.retriever_data.MusicCsvQASrc
    file: /private/home/xilun/hybridqa/musicqa/split/musicqa_dev.tsv

  music_test:
    _target_: dpr.data.retriever_data.MusicCsvQASrc
    file: /private/home/xilun/hybridqa/musicqa/split/musicqa_test.tsv

  tabfact_train_1:
    _target_: dpr.data.retriever_data.TabFactJsonQASrc
    file: /checkpoint/michaelsch/vladimir/tabfact_data/r1_training_all.json

  tabfact_train_2:
    _target_: dpr.data.retriever_data.TabFactJsonQASrc
    file: /checkpoint/michaelsch/vladimir/tabfact_data/r2_training_all.json
