defaults:
  - encoder: hf_bert
  - datasets: retriever_query_src

ctx_sources:
  dpr_wiki:
    _target_: dpr.data.retriever_data.CsvCtxSrc
    file: /private/home/vladk/data/wikipedia/wiki_passages/psgs_w100.tsv
    id_prefix: 'wiki:'

  nq_tables:
    _target_: dpr.data.retriever_data.JsonlTablesCtxSrc
    file: /checkpoint/vladk/datasets/tables/nq_all.tables.jsonl
    tables_chunk_sz: 100
    id_prefix: 'nqt:'

  nq_train_tables:
    _target_: dpr.data.retriever_data.JsonlTablesCtxSrc
    file: /checkpoint/vladk/datasets/tables/nq_train.tables.jsonl
    tables_chunk_sz: 100
    id_prefix: 'nqt:'

  kilt_wiki:
    _target_: dpr.data.retriever_data.KiltCsvCtxSrc
    file: /checkpoint/fabiopetroni/KILT/multitask_dpr_datasets/v0.20200817/chunks.tsv

  wiki_tables:
    _target_: dpr.data.retriever_data.JsonlTablesCtxSrc
    file: /private/home/barlaso/data/wikipedia/tables/wiki_tables.jsonl
    tables_chunk_sz: 100
    id_prefix: 'wt:'

  wiki_with_lists:
    _target_: dpr.data.retriever_data.CsvCtxSrc
    file: /private/home/barlaso/data/wikipedia/passages_with_lists_w100.tsv
    id_prefix: 'wikil:'

  wiki_info_boxes:
    _target_: dpr.data.retriever_data.JsonlTablesCtxSrc
    file: /private/home/barlaso/data/wikipedia/wiki.infoboxes.20181220.dump.jsonl
    tables_chunk_sz: 100
    id_prefix: 'wib:'

indexers:
  flat:
    _target_: dpr.indexer.faiss_indexers.DenseFlatIndexer

  hnsw:
    _target_: dpr.indexer.faiss_indexers.DenseHNSWFlatIndexer

  hnsw_sq:
    _target_: dpr.indexer.faiss_indexers.DenseHNSWSQIndexer


qa_dataset:
ctx_datatsets:

#Glob paths to encoded passages (from generate_dense_embeddings tool)
encoded_ctx_files: []

out_file:
# "regex" or "string"
match: string
n_docs: 100
validation_workers: 16
batch_size: 128
do_lower_case: True
save_or_load_index: False
kilt_out_file:
model_file:
validate_as_tables: False
rpc_retriever_cfg_file:
indexer: flat

special_tokens:
  - '[Q]'
  - '[R]'
  - '[F]'
  - '[START_ENT]'
  - '[END_ENT]'
  - '[D]'

# TODO: move to a sub conf
local_rank: -1
global_loss_buf_sz: 150000
device:
distributed_world_size:
no_cuda: False
n_gpu:
fp16: False
fp16_opt_level: O1

